spring.application.name=eticketing-backend
server.port=${BACKEND_PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/eticketing}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.security=INFO
